// <auto-generated />
namespace QEMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Severitychangefromstringtoint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Severitychangefromstringtoint));
        
        string IMigrationMetadata.Id
        {
            get { return "202002041735109_Severity change from string to int"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
