// <auto-generated />
namespace QEMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MakingTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MakingTables));
        
        string IMigrationMetadata.Id
        {
            get { return "202001302154462_Making Tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
